version: '3'

services:
  neo4j:
    image: neo4j:3.5
    container_name: neo4j
    restart: always
    network_mode: bridge
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
    - ./_/neo4j/data:/data